train:
  epochs: 200
  batch_size: 16
  lr: 0.001
  itr_per_epoch: 100000000
diffusion:
  layers: 4
  channels: 64
  nheads: 8
  diffusion_embedding_dim: 128
  beta_start: 0.0001
  beta_end: 0.5
  lambda_freq: 0.05
  num_steps: 50
  ode_steps: 50
  schedule: quad
  is_linear: false
  freq_noise: false
  freq_shaping_gamma: 0.0
  seq_len: 48
model:
  is_unconditional: false
  timeemb: 128
  featureemb: 16
  target_strategy: random
